# Generated by Django 4.0 on 2021-12-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productvariant_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantprice',
            name='title',
        ),
    ]
